version: '3.7'

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: 100M

services:
  server:
    image: judge0/judge0:1.13.0
    volumes:
      - ../judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    logging: *default-logging
    restart: always
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0
      - REDIS_PASSWORD=judge0
    depends_on:
      - db
      - redis

  workers:
    image: judge0/judge0:1.13.0
    command: ["./scripts/workers"]
    volumes:
      - ../judge0.conf:/judge0.conf:ro
    privileged: true
    logging: *default-logging
    restart: always
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0
      - REDIS_PASSWORD=judge0
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.0
    env_file: ../judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    logging: *default-logging
    restart: always
    environment:
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0

  redis:
    image: redis:6.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "judge0"'
    ]
    volumes:
      - redis-data:/data
    logging: *default-logging
    restart: always

volumes:
  postgres-data:
  redis-data: